### ISSUE TITLE
imv capture wm's key bindings

### ISSUE THREAD

**Issue by n3f4s** [eXeC64/imv#108]
Hi,

I'm using ``i3`` window manager. I use (most of the time) ``alt + <right/left arrow>`` to switch between window.
When I switch the focus _to_ or _from_ a ``imv`` window, ``imv`` change the next or previous image.
For example, if I have two window : on the left some window and on the right imv. If the focus is on the left windows and I press ``alt + <right arrow>``, the focus will go to the ``imv`` window (which is the expected behaviour) and ``imv`` will go to the next image (which is not the expected behaviour).

``imv`` as the same behaviour when losing focus (and with both right and left arrow key).

Since ``alt + <right/left arrow>`` is used by ``i3``, it should not trigger anything in ``imv``. ``imv`` is the only software that I've seen "capturing" ``i3`` bindings so this does not look like it's a bug from ``i3``.

**Comment by ainola** [comment]
Confirmed, but for me it's <super>+{h,j,k,l} for window movement in i3. When I move from one window to an imv window, the image moves one keypress in the respective direction.

**Comment by vyp** [comment]
I have the same issue as @ainola with super + {h, j, k, l} for window movement in herbstluftwm.

**Comment by eXeC64** [comment]
Thanks for the detailed report. I've recently done a large refactor of imv. Is this bug still affecting you?

This is something I'd like to get fixed before releasing v3 of imv.

**Comment by ainola** [comment]
I just compiled the latest master commit and have experienced the same issue.

**Comment by n3f4s** [comment]
Same, I still the issue with the latest master commit and with ``awesome`` too (latest master commit).

**Comment by eXeC64** [comment]
Should be fixed by c51dff6a4e5bd21491bb0c085cb08f35275332a0

Please test and confirm this

**Comment by ainola** [comment]
Yep! Looks great! It also fixes the issue where pressing 'q' would quit multiple windows instead of just one.

Thanks for this!

**Comment by eXeC64** [comment]
Fantastic

**Comment by n3f4s** [comment]
I still have the bug when I move the ``imv`` window in and out of a container (with ``i3``).

To reproduce the bug, you can open a terminal, start ``imv``. The two windows are side by side, ``imv`` on the right. When you move the ``imv`` window on the left (``Mod+Shift+Left``), ``imv`` change to the previous image.

I'm trying to make a video of the issue but my computer is quite old so it might take a little time.

**Comment by ainola** [comment]
n3f4s is correct: Moving the window itself (shift+super+h/j/k/l for me in i3) does make it move.

**Comment by n3f4s** [comment]
[c51dff6](https://github.com/eXeC64/imv/commit/c51dff6a4e5bd21491bb0c085cb08f35275332a0) is about focus issues. The issue here is that ``imv`` shouldn't receive event used by the window manager. Here the keystroke to move the (``imv``) window should not be captured by ``imv``. They shouldn't appear in the event queue. It's possible that it is a SDL2 bug since ``imv`` shouldn't be able to poll those event.

**Comment by eXeC64** [comment]
It's frustrating that c51dff6 exists at all. We shouldn't be second guessing the events passed by SDL. The proper course here is to identify and fix the underlying bug in SDL2, or X11, wherever the rogue events are coming from. c51dff6 is always going to be a stop-gap at best. It helps with the symptoms with no visible side effects, but doesn't solve the problem.

I don't think it's appropriate to add more hacks like this to imv, and in due course c51dff6 ought to be removed when the underlying bug is resolved upstream.

**Comment by n3f4s** [comment]
I agree with you with the course of action. Trying to patch things in `imv` is hacky and you can't fix everything from `imv` (e.g. you don't know, in imv, if a keystroke is used by the window manager).

However I think you should leave this issue open until the bug is fixed in the source (`SDL`, `X11`, ...). Or at least until a bug report is filed.

**Comment by eXeC64** [comment]
Reopening until upstream fixes - hopefully it'll stop this getting duplicate reports as well.

**Comment by n3f4s** [comment]
There is a bug report on SDL's bug tracker [here](https://bugzilla.libsdl.org/show_bug.cgi?id=3784).

**Comment by eXeC64** [comment]
Removing from v3 plan - there's nothing I can do, short of debugging and fixing X11 myself it seems.

**Comment by ainola** [comment]
Thank you for your work on this despite the issue lying much deeper.

**Comment by eXeC64** [comment]
The SDL bug linked above appears to have been abandoned. Closing this issue. If you're affected, I recommend reopening the SDL bug that's the root cause.
